apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deepseek-agent.fullname" . }}-cluster-role
  labels:
    {{- include "deepseek-agent.labels" . | nindent 4 }}
rules:
  # 允许获取当前命名空间或集群的 Pod 和 Service
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  # 允许获取集群节点（Nodes）信息（属于集群级别资源）
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  # 允许获取 metrics-server 提供的集群节点与 Pod 内存/CPU 监控指标
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "deepseek-agent.fullname" . }}-cluster-rolebinding
  labels:
    {{- include "deepseek-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}  # 绑定到 ai-agent 命名空间下的 default SA
roleRef:
  kind: ClusterRole
  name: {{ include "deepseek-agent.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io