apiVersion: external-secrets.io/v1
Kind: SecretStore
metadata:
  Name: aws-secretsmanager
  Namespace: {{ .Release.Namespace }}
spec:
  Provider:
    Aws:
      Auth:
        Jwt:
          Service Account Ref:
            Name: external-secrets-sa
            Namespace: external-secrets 
      Region: us-east-1
      Service: SecretsManager