apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepseek-agent
  namespace: argocd  
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default

  source:
    repoURL: https://github.com/pengchao2022/deepseek-ai-agent-cd.git
    targetRevision: HEAD 
    path: manifests

    helm:
      values: |
        global:
          environment: production

  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: deepseek-agent-prod             

  syncPolicy:
    automated:
      prune: true     
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true  